### ISSUE TITLE
TODO: Week 1

### ISSUE THREAD

**Issue by laureanray** [laureanray/cores-pwa#3]
**Expected Deliverables by Friday**
@mxrkjxy 

- [ ] Finalize the sidebar

- [ ] Optimize font for different devices

- [ ] Add Media Query for Desktops/Web Browser

- [ ] Create spinners/loaders

- [ ] Create a placeholder image for the sidebar
